name: 01 Building Blocks
run-name: Terraform Build Testing by ${{ github.actor }} ðŸš€
on:
  workflow_call:
  #push:
   # branches:
   #   - main
jobs:
  Setup Terraform:
    name: Terraform Setup
    runs-on: macos-14
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Output Results
        run: |
          echo ${{ steps.plan.outputs.stdout }}
          echo ${{ steps.plan.outputs.stderr }}
          echo ${{ steps.plan.outputs.exitcode }}

#  Test:
#    name: Test Environments
#    runs-on: ubuntu-latest
#    environment: Test
#    needs: Setup Terraform
#    steps:
#      - run: |
#          echo "Hello ${{vars.WHO_TO_GREET}} from ${{github.actor}}."
#          sec=$(echo ${{secrets.MY_SECRET}} | sed 's/./& /g')
#          echo "My Secret is '$sec'."
#
#  Load-Test:
#    name: Load-Test Environments
#    runs-on: ubuntu-latest
#    environment: Load-Test
#    needs: My-First-Job
#    steps:
#      - run: |
#          echo "Hello ${{vars.WHO_TO_GREET}} from ${{github.actor}}."
#          sec=$(echo ${{secrets.MY_SECRET}} | sed 's/./& /g')
#          echo "My Secret is '$sec'."
#  Production:
#    name: Production Environments
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      pull-requests: write
#    environment:
#      name: Production
#      url: https://writeabout.net
#    needs: [Test, Load-Test]
#    steps:
#      - uses: actions/checkout@v4.1.0
#      - uses: devops-actions/actionlint@v0.1.2
#      - run: |
#          echo "Hello ${{vars.WHO_TO_GREET}} from ${{github.actor}}."
#          sec=$(echo ${{secrets.MY_SECRET}} | sed 's/./& /g')
#          echo "My Secret is '$sec'."
#
#  My-Second-Job:
#    name: Second Job
#    needs:
#      - My-First-Job
#    runs-on: ubuntu-latest
#    steps:
#      - name: List Files in the Repository
#        run: |
#           echo "The Repository ${{github.repository}} contains the following files"
#           tree
#  My-Third-Job:
#    name: Print Variables & Secrets
#    runs-on: macos-latest
#    steps:
#      - name: Echo Variable
#        run:
#          echo "Hello ${{vars.WHO_TO_GREET}} from ${{github.actor}}"
#      - name: Echo Secrets
#        run:
#          echo "My Secret is ${{secrets.MY_SECRET}}"