name: 01 Building Blocks
on: workflow_call
jobs:
  My-First-Job:
    name: First Job
    runs-on: macos-14
    steps:
      - name: Echo Hello World
        run: echo "Hello World!"
  My-Second-Job:
    name: Second Job
    needs:
      - My-First-Job
    runs-on: ubuntu-latest
    steps:
      - name: Echo Fail
        run: |
           echo "I will fail"
           exit 0
      - name: Echo Pass
        run: echo "I will pass"