name: 01 Building Blocks
on:
  push:
    branches:
      - main
jobs:
  My-First-Job:
    name: First Job
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - run: echo "Hello World!"
  My-Second-Job:
    name: Second Job
    needs:
      - My-First-Job
    runs-on: ubuntu-latest
    steps:
      - name: List Files in the Repository
        run: |
           echo "The Repository ${{github.repository}} contains the following files"
           tree