name: 01 Building Blocks
on: workflow_call
jobs:
  My-First-Job:
    name: First Job
    runs-on: macos-14
    steps:
      - name:
          Successful Job:
            run: echo "Hello World!"
  My-Second-Job:
    name: Second Job
    needs:
      - My-First-Job
    runs-on: ubuntu-latest
    steps:
      - name:
          Failed step:
            run: |
              - echo "I will fail"
              - exit 1
      - name:
          Say Goodbye:
            run: echo "I will pass"