name: 01 Building Blocks
run-name: Testing Build by ${{ github.actor }} ðŸš€
on:
  push:
    branches:
      - main
jobs:
  My-First-Job:
    name: First Job
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - run: echo "Hello World!"
  My-Second-Job:
    name: Second Job
    needs:
      - My-First-Job
    runs-on: ubuntu-latest
    steps:
      - name: List Files in the Repository
        run: |
           echo "The Repository ${{github.repository}} contains the following files"
           tree
  My-Third-Job:
    name: Print Variables & Secrets
    runs-on: macos-latest
    steps:
      - name: Echo Variable
        run:
          echo "Hello ${{vars.WHO_TO_GREET}} from ${{github.actor}}"
      - name: Echo Secrets
        run:
          echo "My Secret is ${{secrets.MY_SECRET}}"