name: Ansible Network Security Audits
run-name: Ansible Security Audit Deployment by ${{ github.actor }} ðŸš€
on:
  workflow_dispatch:

jobs:
  Ansible-Audit:
    name: 'Run Security Audit'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Azure Dependencies
        run: |
          ansible-galaxy collection install azure.azcollection --force
          COLLECTION_PATH=$(ansible-config dump | grep COLLECTIONS_PATHS | cut -d '=' -f2 | tr -d ' ' | cut -d ':' -f1 | sed "s|~|$HOME|")
          REQUIREMENTS_FILE="$COLLECTION_PATH/ansible_collections/azure/azcollection/requirements-azure.txt"
          pip install -r "$REQUIREMENTS_FILE"

      - name: Execute Network Audit Playbook
        run: |
          ansible-playbook ./Ansible/network_audit.yml -e "ansible_python_interpreter=$(which python3)"
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_SECRET: ${{ secrets.AZURE_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}