name: Ansible Network Security Audits
run-name: Ansible Security Audit Deployment by ${{ github.actor }} ðŸš€
on:
  workflow_dispatch:
jobs:
  Ansible-Audit:
    name: 'Run Security Audit'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Azure Python SDK
        run: |
          ansible-galaxy collection install azure.azcollection -p ./collections
          pip install -r ./collections/ansible_collections/azure/azcollection/requirements-azure.txt

      - name: Install Azure Collection
        run: ansible-galaxy collection install azure.azcollection

      - name: Execute Network Audit Playbook
        run: |
          export ANSIBLE_COLLECTIONS_PATH=./collections
          ansible-playbook ./Ansible/network_audit.yml -e "ansible_python_interpreter=$(which python3)"
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
