name: 02-ansible-network-audit.yml
run-name: Ansible Security Audit Deployment by ${{ github.actor }} ðŸš€
on:
  workflow_dispatch:
jobs:
  Ansible-Audit:
    name: 'Run Security Audit'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Azure Collection
        run: ansible-playbook ./Ansible/network_audit.yml
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
